### ISSUE TITLE
Switch dependencies

### ISSUE THREAD

**Issue by vankasteelj** [roecrew/magsearch#1]
Hi, I saw your package on npm. I see you rely on torrent-health. 

It's somewhat outdated (and doesn't function correctly, you may have noticed that). 

I came here to suggest you to switch to torrent-tracker-health, which I took under my account for maintenance.

**Comment by maelswarm** [comment]
I fixed torrent-health a month or so back. What problems have you been noticing?

**Comment by vankasteelj** [comment]
I saw you still depended on torrent-health dating from 2 years, that's all. Just giving you a heads up that a maintained version was out

**Comment by maelswarm** [comment]
If I run into any problems I'll def check yours out.
